// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9t-1KAWCPxCcR7J9G903-T--1YVP9ns',
    appId: '1:101972822228:web:15572568814627a249d341',
    messagingSenderId: '101972822228',
    projectId: 'task2-pam',
    authDomain: 'task2-pam.firebaseapp.com',
    storageBucket: 'task2-pam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWzaxTcDD3umV7QnL2Nsg41bniQvARsBA',
    appId: '1:101972822228:android:a1fdd9c44ab1ffe949d341',
    messagingSenderId: '101972822228',
    projectId: 'task2-pam',
    storageBucket: 'task2-pam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY1OEkWNMAT9yMNrGkvSA5VEVnqtO68pE',
    appId: '1:101972822228:ios:2411d7a8fc6534aa49d341',
    messagingSenderId: '101972822228',
    projectId: 'task2-pam',
    storageBucket: 'task2-pam.appspot.com',
    iosBundleId: 'com.example.stopwatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY1OEkWNMAT9yMNrGkvSA5VEVnqtO68pE',
    appId: '1:101972822228:ios:2411d7a8fc6534aa49d341',
    messagingSenderId: '101972822228',
    projectId: 'task2-pam',
    storageBucket: 'task2-pam.appspot.com',
    iosBundleId: 'com.example.stopwatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9t-1KAWCPxCcR7J9G903-T--1YVP9ns',
    appId: '1:101972822228:web:c24a28e164592da749d341',
    messagingSenderId: '101972822228',
    projectId: 'task2-pam',
    authDomain: 'task2-pam.firebaseapp.com',
    storageBucket: 'task2-pam.appspot.com',
  );
}
